version: '3.1'

services:
  db:
    ports: 
      - 3306:3306
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
    volumes:
      - "./mysql:/docker-entrypoint-initdb.d/:ro"

